module Gesso
  VERSION: String
  class Sketch
    def save_gif: (String path, ?frames: Integer, ?fps: Numeric, ?loop: bool | Integer) -> String
    def gif_frames_remaining: () -> Integer?
    def close: (?discard: bool) -> untyped
  end
end
